behaviors:
  PPO_6_5:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 1.0e-4
      learning_rate_schedule: linear

      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple

    checkpoint_interval: 300000
    max_steps: 1800000 #1500 * 1000
    time_horizon: 64
    summary_freq: 50000 #every 10
    keep_checkpoints: 5

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0


  PPO_6_5_2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple

    checkpoint_interval: 300000
    max_steps: 1800000 #1500 * 1000
    time_horizon: 64
    summary_freq: 50000 #every 10
    keep_checkpoints: 5

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0


  PPO_6_5_3:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 5.0e-4
      learning_rate_schedule: linear

      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple

    checkpoint_interval: 300000
    max_steps: 1800000 #1500 * 1000
    time_horizon: 64
    summary_freq: 50000 #every 10
    keep_checkpoints: 5

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0