behaviors:
  CarAgent5_1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      beta: 5.0e-3
      beta_schedule: constant
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      
    network_settings:
      normalize: false
      hidden_units: 16
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    checkpoint_interval: 200000
    max_steps: 1200000 #3000 * 400
    time_horizon: 64
    summary_freq: 60000 #every 10