behaviors:
  CarAgent5_1:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 100000
      learning_rate: 0.0003
      learning_rate_schedule: linear

      buffer_init_steps: 3000
      tau: 0.05
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 10.0
      
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2

    max_steps: 600000 #3000 * 200
    time_horizon: 1000
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    init_path: null

    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0

      #curiosity:
      #  strength: 0.02
      #  gamma: 0.99
      #  encoding_size: 256
      #  learning_rate: 3.0e-4