behaviors:
  PPO_CarAgent6:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      
    network_settings:
      normalize: false
      hidden_units: 16
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    checkpoint_interval: 200000
    max_steps: 1200000 #3000 * 400
    time_horizon: 64
    summary_freq: 60000 #every 10

  SAC_CarAgent6:
    trainer_type: sac
    hyperparameters:
      batch_size: 256
      buffer_size: 100000
      learning_rate: 0.0003
      learning_rate_schedule: constant

      buffer_init_steps: 3000
      tau: 0.05
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 10.0
      
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 16
      num_layers: 2

    max_steps: 600000 #3000 * 200
    time_horizon: 1000
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    init_path: null

    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0

      #curiosity:
      #  strength: 0.02
      #  gamma: 0.99
      #  encoding_size: 256
      #  learning_rate: 3.0e-4
