behaviors:
  CarAgent5_1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 0.0004
      beta: 0.005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      #curiosity:
      #  strength: 0.02
      #  gamma: 0.99
      #  encoding_size: 256
    checkpoint_interval: 200000
    max_steps: 3000000 #3000 * 700
    time_horizon: 64
    summary_freq: 60000 #every 10