behaviors:
  SAC_CarAgent6_1:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 50000
      learning_rate: 0.0003
      learning_rate_schedule: constant

      buffer_init_steps: 10000
      tau: 0.005
      steps_per_update: 20.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 20.0
      
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 64
      num_layers: 2

    max_steps: 240000 #3000 * 200
    time_horizon: 1000
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    init_path: null

    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
