behaviors:
  SAC_CarAgent6:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 50000
      learning_rate: 3.0e-4
      learning_rate_schedule: constant

      buffer_init_steps: 10000
      tau: 0.005
      save_replay_buffer: false
      init_entcoef: 0.5
      steps_per_update: 20.0
      reward_signal_steps_per_update: 20.0
      
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple

    checkpoint_interval: 50000
    max_steps: 400000
    time_horizon: 64
    summary_freq: 50000
    keep_checkpoints: 5

    threaded: false
    init_path: null

    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
